# Generated by Django 3.1.8 on 2021-12-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infor',
            name='month_details',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
