# Generated by Django 3.1.8 on 2022-02-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_infor_month_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=19)),
                ('name', models.CharField(max_length=19)),
                ('date', models.DateField(auto_now_add=True)),
                ('phone', models.CharField(max_length=19)),
                ('address', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('location', models.CharField(max_length=99)),
            ],
        ),
    ]
