# Generated by Django 3.1.8 on 2022-02-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_upload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='upload',
            new_name='uploadsss',
        ),
    ]
